### ISSUE TITLE
Non-Intel breakages on openSUSE in test_platform_linux[case7]

### ISSUE THREAD

**Issue by jayvdb** [asottile/pip-custom-platform#31]
Packaged at https://build.opensuse.org/package/show/home:jayvdb:py-new/python-pip-custom-platform

There are a lot of failures in `test_platform_linux` due to different arch, e.g. on ppc

```py
[  119s] __________________________ test_platform_linux[case7] __________________________
[  119s] 
[  119s] mock_distro = <MagicMock name='distro' id='140736209194344'>
[  119s] mock_platform = <MagicMock name='platform' id='140736209215048'>
[  119s] case = SystemTestCase(docker_image='base/archlinux', mock_id='arch', mock_version='', expected_platform_name='linux_x86_64', setup_script=('pacman -Syy >&2', 'pacman -S --noconfirm python python-pip >&2'))
[  119s] 
[  119s]     @pytest.mark.parametrize('case', SYSTEM_TESTCASES)
[  119s]     @mock.patch('pip_custom_platform.default_platform.platform')
[  119s]     @mock.patch('pip_custom_platform.default_platform.distro')
[  119s]     def test_platform_linux(mock_distro, mock_platform, case):
[  119s]         mock_distro.id.return_value = case.mock_id
[  119s]         mock_distro.version.return_value = case.mock_version
[  119s]         mock_platform.system.return_value = 'Linux'
[  119s]         mock_platform.machine.return_value = 'x86_64'
[  119s] >       assert default_platform_name() == case.expected_platform_name
[  119s] E       AssertionError: assert 'linux_ppc64le' == 'linux_x86_64'
[  119s] E         - linux_ppc64le
[  119s] E         + linux_x86_64
```

On s390x

```py
[   66s] E       AssertionError: assert 'linux_s390x' == 'linux_x86_64'
[   66s] E         - linux_s390x
[   66s] E         + linux_x86_64
```

I expect this only needs a minor fix in the tests, or even skip it on non-Intel platforms if that case is intel specific.

fwiw, pymonkey is passing all tests on all openSUSE current platforms (except armv7l not yet built)
https://build.opensuse.org/package/show/home:jayvdb:py-new/python-pymonkey

**Comment by asottile** [comment]
yeah there's no intention to test on anything other than x86_64 -- it does work on other platforms (and macos even and probably windows) but it's not worth the effort to test there

**Comment by asottile** [comment]
that said, if you want this, send a patch and I'll consider it

**Comment by jayvdb** [comment]
Of course I want it.  But if you close issues about valid problems others face, it does not bode well for its maintenance.  Kinda odd that a project called "foo-custom-platform" rejects issues about non-x86_64.

**Comment by asottile** [comment]
First off, I understand we appear to have gotten off on the wrong foot, please do not take my comments personally and I hope that we can work amicably now and in the future.

if you consult the README it gives an explanation of the goal this tool targets, handling architecture is not one of them since that's already solved by the vanilla tools

I do not have access to non-x86_64 and therefore it is prohibitively difficult for me to test against and downright frustrating to attempt to write code targetting it.  I am not gifted with a rack of arm / Z / ppc / etc. hosts which I can use to test.  And unless they're exposing actual bugs in the implementation it's not worth the greenhouse gasses, effort, or even the discussion.

I closed this issue because I don't care about the outcome of it, I have no intention myself to work on it and it doesn't affect the correctness of the tool.  And that the goal of the tool is to handle the ambiguity of linux_x86_64 (even though it may work fine on other architectures / platforms)

If you can point out where this is a valid problem I'll reopen, but an exotic architecture test failure (in which the actual functionality probably actually works just fine) is not a helpful issue.  I'd be especially amenable if you lead with a useful patch / etc. to help work towards it.  I'm constantly bombarded with packagers which don't put in basic effort to try and solve problems themselves / improve the ecosystem :(  Please understand this is free software and apologies if this looks personal
